// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/poll"
	"backend/ent/polloption"
	"backend/ent/vote"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PollCreate is the builder for creating a Poll entity.
type PollCreate struct {
	config
	mutation *PollMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *PollCreate) SetTitle(v string) *PollCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PollCreate) SetDescription(v string) *PollCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PollCreate) SetNillableDescription(v *string) *PollCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPollType sets the "poll_type" field.
func (_c *PollCreate) SetPollType(v string) *PollCreate {
	_c.mutation.SetPollType(v)
	return _c
}

// SetNillablePollType sets the "poll_type" field if the given value is not nil.
func (_c *PollCreate) SetNillablePollType(v *string) *PollCreate {
	if v != nil {
		_c.SetPollType(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PollCreate) SetCreatedBy(v string) *PollCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *PollCreate) SetNillableCreatedBy(v *string) *PollCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetMaxVotesPerUser sets the "max_votes_per_user" field.
func (_c *PollCreate) SetMaxVotesPerUser(v int) *PollCreate {
	_c.mutation.SetMaxVotesPerUser(v)
	return _c
}

// SetNillableMaxVotesPerUser sets the "max_votes_per_user" field if the given value is not nil.
func (_c *PollCreate) SetNillableMaxVotesPerUser(v *int) *PollCreate {
	if v != nil {
		_c.SetMaxVotesPerUser(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *PollCreate) SetExpiresAt(v time.Time) *PollCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *PollCreate) SetNillableExpiresAt(v *time.Time) *PollCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PollCreate) SetCreatedAt(v time.Time) *PollCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PollCreate) SetNillableCreatedAt(v *time.Time) *PollCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PollCreate) SetUpdatedAt(v time.Time) *PollCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PollCreate) SetNillableUpdatedAt(v *time.Time) *PollCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddOptionIDs adds the "options" edge to the PollOption entity by IDs.
func (_c *PollCreate) AddOptionIDs(ids ...int) *PollCreate {
	_c.mutation.AddOptionIDs(ids...)
	return _c
}

// AddOptions adds the "options" edges to the PollOption entity.
func (_c *PollCreate) AddOptions(v ...*PollOption) *PollCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOptionIDs(ids...)
}

// AddVoteIDs adds the "votes" edge to the Vote entity by IDs.
func (_c *PollCreate) AddVoteIDs(ids ...int) *PollCreate {
	_c.mutation.AddVoteIDs(ids...)
	return _c
}

// AddVotes adds the "votes" edges to the Vote entity.
func (_c *PollCreate) AddVotes(v ...*Vote) *PollCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVoteIDs(ids...)
}

// Mutation returns the PollMutation object of the builder.
func (_c *PollCreate) Mutation() *PollMutation {
	return _c.mutation
}

// Save creates the Poll in the database.
func (_c *PollCreate) Save(ctx context.Context) (*Poll, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PollCreate) SaveX(ctx context.Context) *Poll {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PollCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PollCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PollCreate) defaults() {
	if _, ok := _c.mutation.PollType(); !ok {
		v := poll.DefaultPollType
		_c.mutation.SetPollType(v)
	}
	if _, ok := _c.mutation.MaxVotesPerUser(); !ok {
		v := poll.DefaultMaxVotesPerUser
		_c.mutation.SetMaxVotesPerUser(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := poll.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := poll.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PollCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Poll.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := poll.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Poll.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PollType(); !ok {
		return &ValidationError{Name: "poll_type", err: errors.New(`ent: missing required field "Poll.poll_type"`)}
	}
	if _, ok := _c.mutation.MaxVotesPerUser(); !ok {
		return &ValidationError{Name: "max_votes_per_user", err: errors.New(`ent: missing required field "Poll.max_votes_per_user"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Poll.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Poll.updated_at"`)}
	}
	return nil
}

func (_c *PollCreate) sqlSave(ctx context.Context) (*Poll, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PollCreate) createSpec() (*Poll, *sqlgraph.CreateSpec) {
	var (
		_node = &Poll{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(poll.Table, sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(poll.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(poll.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.PollType(); ok {
		_spec.SetField(poll.FieldPollType, field.TypeString, value)
		_node.PollType = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(poll.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.MaxVotesPerUser(); ok {
		_spec.SetField(poll.FieldMaxVotesPerUser, field.TypeInt, value)
		_node.MaxVotesPerUser = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(poll.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(poll.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(poll.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   poll.OptionsTable,
			Columns: []string{poll.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(polloption.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   poll.VotesTable,
			Columns: []string{poll.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PollCreateBulk is the builder for creating many Poll entities in bulk.
type PollCreateBulk struct {
	config
	err      error
	builders []*PollCreate
}

// Save creates the Poll entities in the database.
func (_c *PollCreateBulk) Save(ctx context.Context) ([]*Poll, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Poll, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PollMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PollCreateBulk) SaveX(ctx context.Context) []*Poll {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PollCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PollCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
