// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/poll"
	"backend/ent/polloption"
	"backend/ent/vote"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Vote is the model entity for the Vote schema.
type Vote struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Anonymous identifier for the voter (IP, session, etc.)
	VoterIdentifier string `json:"voter_identifier,omitempty"`
	// When the vote was cast
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VoteQuery when eager-loading is set.
	Edges             VoteEdges `json:"edges"`
	poll_votes        *int
	poll_option_votes *int
	selectValues      sql.SelectValues
}

// VoteEdges holds the relations/edges for other nodes in the graph.
type VoteEdges struct {
	// The poll this vote belongs to
	Poll *Poll `json:"poll,omitempty"`
	// The option this vote is for
	Option *PollOption `json:"option,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PollOrErr returns the Poll value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteEdges) PollOrErr() (*Poll, error) {
	if e.Poll != nil {
		return e.Poll, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: poll.Label}
	}
	return nil, &NotLoadedError{edge: "poll"}
}

// OptionOrErr returns the Option value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteEdges) OptionOrErr() (*PollOption, error) {
	if e.Option != nil {
		return e.Option, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: polloption.Label}
	}
	return nil, &NotLoadedError{edge: "option"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Vote) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case vote.FieldID:
			values[i] = new(sql.NullInt64)
		case vote.FieldVoterIdentifier:
			values[i] = new(sql.NullString)
		case vote.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case vote.ForeignKeys[0]: // poll_votes
			values[i] = new(sql.NullInt64)
		case vote.ForeignKeys[1]: // poll_option_votes
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Vote fields.
func (_m *Vote) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case vote.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case vote.FieldVoterIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field voter_identifier", values[i])
			} else if value.Valid {
				_m.VoterIdentifier = value.String
			}
		case vote.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case vote.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field poll_votes", value)
			} else if value.Valid {
				_m.poll_votes = new(int)
				*_m.poll_votes = int(value.Int64)
			}
		case vote.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field poll_option_votes", value)
			} else if value.Valid {
				_m.poll_option_votes = new(int)
				*_m.poll_option_votes = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Vote.
// This includes values selected through modifiers, order, etc.
func (_m *Vote) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPoll queries the "poll" edge of the Vote entity.
func (_m *Vote) QueryPoll() *PollQuery {
	return NewVoteClient(_m.config).QueryPoll(_m)
}

// QueryOption queries the "option" edge of the Vote entity.
func (_m *Vote) QueryOption() *PollOptionQuery {
	return NewVoteClient(_m.config).QueryOption(_m)
}

// Update returns a builder for updating this Vote.
// Note that you need to call Vote.Unwrap() before calling this method if this Vote
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Vote) Update() *VoteUpdateOne {
	return NewVoteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Vote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Vote) Unwrap() *Vote {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Vote is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Vote) String() string {
	var builder strings.Builder
	builder.WriteString("Vote(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("voter_identifier=")
	builder.WriteString(_m.VoterIdentifier)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Votes is a parsable slice of Vote.
type Votes []*Vote
